### ISSUE TITLE
Develop locally without SSL

### ISSUE THREAD

**Issue by nambrot** [TheGiftsProject/omniauth-ebay#3]
Hey there,

we'd like to use your omniauth strategy, however it seems like eBay requires the callback to support SSL which doesn't seem to be very common for local development environments. I was just wondering how you guys managed to deal with it.

Nam

**Comment by itayadler** [comment]
We use nginx locally, and we configure it to run an SSL server also (running on port 443 naturally).
Here's what you need to do to make ur nginx do it (can be done also with Apache)
1) Generate a self-signed certificate, use this for reference http://articles.slicehost.com/2007/12/19/ubuntu-gutsy-self-signed-ssl-certificates-and-nginx
2) Copy the certificates to /etc/nginx/ssl
3) In your /etc/nginx/sites-available/"config_file" (usually there's a default there), add something similar to this snippet:

```
  server {
    listen       443 ssl;
    server_name  local.yourappname.com;

    ssl                  on;
    ssl_certificate      ssl/server.crt; #### THE CERTIFICATE YOU GENERATED ####
    ssl_certificate_key  ssl/server.key;  #### THE CERTIFICATE YOU GENERATED ####

    keepalive_timeout 60;
    ssl_session_timeout  5m;

    ssl_protocols  SSLv2 SSLv3 TLSv1;
    ssl_ciphers  ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
    ssl_prefer_server_ciphers   on;
    location / {
        proxy_pass  http://localhost:3019;
        ### force timeouts if one of backend is died ##
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
        ### Set headers ####
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        ### Most PHP, Python, Rails, Java App can use this header ###
        proxy_set_header X-Forwarded-Proto https;
        ### By default we don't want to redirect it ####
        proxy_redirect     off;
    }
  }
```

I hope this will help you :)

**Comment by nambrot** [comment]
Thanks, I followed through and it worked!
